### ISSUE TITLE
Steps for Training Model in Custom Vision APIs should be elaborated in documentation

### ISSUE THREAD

**Issue by abhiongithub** [Microsoft/AIVisualProvision#2]

**Comment by abhiongithub** [comment]
I have trained the model and demo is working and will add the steps with step by step instructions here..

**Comment by cmatskas** [comment]
Hi @abhiongithub thanks for raising this issue. I've added new instructions and linked to our documentation to help with creating and training the Custom Vision model. I hope you'll find them useful and thanks for checking out this project! Feel free to contribute if you have any good ideas
