### ISSUE TITLE
Feature Request: localisation 

### ISSUE THREAD

**Issue by grahamehorner** [Microsoft/AIVisualProvision#6]
at present the visualisation detects English key phases/words to provide an azure resource, please consider other languages in regards to both the apps UI and the within the image take and used to build the azure resource group.

**Comment by dasanagu** [comment]
Hi @grahamehorner! Thank you for the feedback we will be adding this to the backlog, however at this moment we are not planning more development on this code sample app. Thanks!

**Comment by pulimento** [comment]
Hi @grahamehorner! Thank you for the feedback. As David says, there are no plans in development right now. Feel free to send a PR with this feature. Thanks!
