### ISSUE TITLE
Documentation Request : Please add Source of Icons/Images

### ISSUE THREAD

**Issue by AbhiOnGithub** [Microsoft/AIVisualProvision#8]
Please add somewhere guidelines to add new icons /source of icons.
I want to add Icon(s) for the functionality of new Azure components like VMs /  Azure Container instances etc

**Comment by pulimento** [comment]
Hi Abhishek,

Great idea! That info is missing. Icons were provided by a design team.

The guide is: **Use the official icons, with only one flat ink, tinted "Light Blue"** (#3A95FF). The official icons can be found [here](https://www.microsoft.com/en-us/download/details.aspx?id=41937)

For reference, these are the actual icons:
![icons](http://oi66.tinypic.com/alrz8m.jpg)

PS: I saw [your proposed icon](https://github.com/Microsoft/AIVisualProvision/blob/942cf10b058a8d74f5c534d86e8496f719ce0261/Source/VisualProvision.Android/Resources/drawable-hdpi/ic_virtual_machine.png), will work if tinted only with the color mentioned.

Thanks for your time! Closing this now
